<h1>About</h1>

<p>MALgraph is an extension of your MyAnimeList profile, serving you various information about your data&nbsp;&ndash;&nbsp;scores distribution, favorite studios, personalized suggestions and a lot more.</p>

<p>It started as a basic, minimalistic page with black bars, and quickly evolved to a full-fledged MAL data parser. At some point it had too much information to be shown in a single cluster, so we decided to split it into tabs.</p>

<p>History in images: gloomy <a target="_blank" href="<?php echo UrlHelper::absoluteUrl('/media/img/history1.png') ?>">version 1</a>, rich in colors <a target="_blank" href="<?php echo UrlHelper::absoluteUrl('/media/img/history2.png') ?>">version 2</a>. A quick calculation reveals that you&rsquo;re reading version 3 now. Or Mg3, as we call it.</p>

<p>MALgraph uses the following:</p>

<ul>
	<li><a target="_blank" href="http://jquery.com/">jQuery</a>&nbsp;&ndash;&nbsp;because pure JS is like asm nowadays,</li>
	<li><a target="_blank" href="http://php.net/">PHP</a>&nbsp;&ndash;&nbsp;finally, 5.4 introduced short array syntax.</li>
</ul>

<p>Suggestions? Questions? Visit the <a target="_blank" href="http://myanimelist.net/clubs.php?cid=30017">MALgraph club</a> and ask!<br>
We&rsquo;re on <a target="_blank" href="https://github.com/rr-/malgraph4">GitHub</a>, too.</p>

<div id="fb-root"></div>
<script>(function(d, s, id) {
var js, fjs = d.getElementsByTagName(s)[0];
if (d.getElementById(id)) return;
js = d.createElement(s); js.id = id;
js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<div class="fb-like" data-href="https://www.facebook.com/MALgraph" data-send="false" data-width="450" data-show-faces="true"></div>
