<div class="ad" id="adblock-enabled">
	<p>It would be great if you could disable AdBlock on this page. It&rsquo;s just one ad!</p>
	<ul class="horizontal">
		<li>
			<a data-action="agree-auto" href="#">Ok, do it now! (Adblock Plus)</a>
		</li>
		<li>
			<a data-action="agree-manual" href="#">I'll do it myself later!</a>
		</li>
		<li>
			<a data-action="disagree" href="#">Go away, no clicks for you.</a>
		</li>
	</ul>
</div>

<div class="ad" id="google-ads">
	<script type="text/javascript">
		google_ad_client = "ca-pub-4861833348203348"; /* malgraph3-header */
		google_ad_slot = "3987532635";
		google_ad_width = 728;
		google_ad_height = 90;
		adblockHideUrl = <?php echo json_encode(UrlHelper::absoluteUrl('abp:subscribe', ['location' => UrlHelper::absoluteUrl(Config::$mediaUrl . 'adblock.txt'), 'title' => 'MALgraph'])) ?>;
	</script>
	<script type="text/javascript" src="http://pagead2.googlesyndication.com/pagead/show_ads.js"></script>
</div>
