<?php if ($viewContext->contentType == 'image/png'): ?>
<?php readfile(join(DIRECTORY_SEPARATOR, [Config::$mediaDirectory, 'img', 'info-queued.png'])) ?>
<?php return ?>
<?php endif ?>

<div class="section">
	<h2>Okay!</h2>
	<div class="section-body">
		<div style="text-align: center">
		<p>Successfully added <?php echo $viewContext->userName ?> to queue at position <?php echo $viewContext->queuePosition ?>.</p>

		<?php
			$totalMinutes = ceil($viewContext->queuePosition * 5 / max(1, Config::$usersPerCronRun));
			$hours = floor($totalMinutes / 60.);
			$minutes = $totalMinutes % 60;

			$wait = '';
			if ($hours > 0)
			{
				$wait .= $hours . ' hour';
				if ($hours != 1)
					$wait .= 's';
				$wait .= ' ';
			}

			$wait .= $minutes . ' minute';
			if ($minutes != 1)
				$wait .= 's';
		?>

		<p>Since MALgraph processes about <?php echo Config::$usersPerCronRun ?>  users every five minutes,<br>
		this shouldn&rsquo;t take more than <?php echo $wait ?>.</p>
		<p>This page will refresh automatically once your stats are ready.</p>
		</div>

		<script type="text/javascript">
		window.setTimeout(function()
		{
			window.location.reload();
		}, <?php echo 60000 ?>);
		</script>
	</div>
</div>
