<?php if ($viewContext->contentType == 'image/png'): ?>
<?php readfile(join(DIRECTORY_SEPARATOR, [Config::$mediaDirectory, 'img', 'info-queued.png'])) ?>
<?php return ?>
<?php endif ?>

<div class="section">
	<h2>Okay!</h2>
	<div class="section-body">
		<div style="text-align: center">
		<p>Successfully added <?php echo $viewContext->userName ?> to queue at position <?php echo $viewContext->queuePosition ?>.</p>

		<?php $min = ceil($viewContext->queuePosition * 5 / Config::$usersPerCronRun) ?>
		<p>Since MALgraph processes about <?php echo Config::$usersPerCronRun ?>  users every five minutes,<br>
		this shouldn&rsquo;t take more than <?php printf('%d %s', $min, $min > 1 ? 'minutes' : 'minute') ?>.</p>
		<p>This page will refresh automatically once your stats are ready.</p>
		</div>

		<script type="text/javascript">
		window.setTimeout(function()
		{
			window.location.reload();
		}, <?php echo $min * 60000 ?>);
		</script>
	</div>
</div>
