<h1>Privacy policy</h1>

<p>MALgraph downloads and stores publicly available data related to your MyAnimeList account, which are:</p>

<ul>
<li>anime and manga lists,</li>
<li>friends and clubs lists,</li>
<li>profile information (such as nickname, list views, join date, birthday, etc.),</li>
<li>activity history (episodes watched and chapters read) from the last month.</li>
</ul>

<p>In addition, your anime and manga scores are used in the recommendations module, which picks a few dozen random users and bases the suggestions on anonymous scores.</p>

<p>Each refresh of your data, which happens as soon as possible after enqueueing your user name into processing queue, will bump up your list and profile views counters by one. Although we use the API to read your lists, we make sure they&rsquo;re not private by visiting them directly - if they are, their content will be hidden. Note that some parts of this site, e.g. recommendations, will not work with private lists.</p>

<p>In short, you can sleep well - we&rsquo;re not evil and respect your privacy. If you still feel insecure, you can <a target="_blank" href="http://myanimelist.net/mymessages.php?go=send&amp;toname=fri">ask us</a> to block your profile from being displayed here.</p>

<p>Twitter and Facebook share buttons always link back to the tab you&rsquo;re currently in, so you might want to return to the profile before clicking on them.</p>
