<div class="section">
	<h2>Privacy policy</h2>
	<div class="section-body">
		<p>MALgraph downloads and stores publicly available data related to your MyAnimeList account, which are:</p>

		<ul>
		<li>anime and manga lists,</li>
		<li>friends and clubs lists,</li>
		<li>profile information (such as nickname, list views, join date, birthday, etc.),</li>
		<li>activity history (episodes watched and chapters read) from the last month.</li>
		</ul>

		<p>We have to make sure your lists aren&rsquo;t private, so each refresh of your data (soon after adding you to the queue) will bump up your list and profile views counters by one. The content of private lists will be hidden, and recommendations won&rsquo;t be available.</p>

		<p>In short, you can sleep well - we&rsquo;re not evil and respect your privacy. If you still feel insecure, you can ask us to block your profile from being displayed here by sending an e-mail at <?= EmailObfuscator::embedJavascript(Config::$mail) ?>.</p>
	</div>
</div>

<div class="section">
	<h2>Cookies</h2>
	<div class="section-body">
		<p>By European Union&rsquo;s definition, cookies are extremely dangerous shards of pure evil scattered around the Internet, and pages hosted within EU have to put a warning regarding user&rsquo;s safety.</p>

		<p>These crunchy things are used by Analytics to give us feedback about the usage, and by AdSense to show you advertisement banners that you probably blocked and caused us to starve. <a href="http://www.google.com/policies/privacy/partners/" target="_blank">Click here</a> to learn more.</p>

		<p>If you want, you can block accepting cookies in your browser&rsquo;s settings, limiting the browsing experience at the same time. But hey, safety first!</p>
	</div>
</div>
