<div class="actions">
	<div>
		<ul>
			<?php if ($viewContext->module == 'UserControllerProfileModule'): ?>
				<li class="active">
			<?php else: ?>
				<li>
			<?php endif ?>
				<a class="waitable" href="<?php echo UserControllerProfileModule::url($viewContext->user->name) ?>">
					<?php echo UserControllerProfileModule::getText($viewContext, null) ?>
					<i class="icon-menu-profile"></i>
				</a>
			</li>
		</ul>
	</div>

	<?php foreach (Media::getConstList() as $media): ?>
		<hr>
		<div class="<?php echo Media::toString($media) ?>">
			<ul>
				<?php foreach (UserController::getAvailableModules() as $module): ?>
					<?php if (in_array($media, $module::getMediaAvailability())): ?>
						<?php if ($viewContext->module == $module and $viewContext->media == $media): ?>
							<li class="active">
						<?php else: ?>
							<li>
						<?php endif ?>
							<a class="waitable" href="<?php echo $module::url($viewContext->user->name, $media) ?>">
								<?php echo $module::getText($viewContext, $media) ?>
								<i class="icon-menu-<?php $x = explode(' ', strtolower($module::getText($viewContext, $media))); echo end($x) ?>"></i>
							</a>
						</li>
					<?php endif ?>
				<?php endforeach ?>
			</ul>
		</div>
	<?php endforeach ?>
	<div class="clear"></div>
</div>

<!--
<div class="share">
	<p>Share:</p>
	<ul>
		<li>
			<a data-tooltip="Share on Twitter" target="_blank" href="https://twitter.com/intent/tweet?url=<?php echo rawurlencode(UrlHelper::currentUrl()) ?>">
				<i class="icon-twitter"></i>
			</a>
		</li>
		<li>
			<a data-tooltip="Share on Facebook" target="_blank" href="http://www.facebook.com/sharer.php?u=<?php echo rawurlencode(UrlHelper::currentUrl()) ?>&amp;t=Share+MALgraph">
				<i class="icon-facebook"></i>
			</a>
		</li>
	</ul>
</div>
-->

<input type="hidden" id="user-id" value="<?php echo $viewContext->user->id ?>">
<input type="hidden" id="user-name" value="<?php echo $viewContext->user->name ?>">
<input type="hidden" id="media" value="<?php echo Media::toString($viewContext->media) ?>">
