<div class="section missing">
	<h2>
		<i data-tooltip="List of titles related to those you have on your list, sorted by score." class="icon-tooltip"></i>
		Missing titles
	</h2>
	<div class="section-body">
		<?php if (empty($viewContext->franchises)): ?>
			<p>Yay! No missing relations!</p>
		<?php elseif ($viewContext->private): ?>
			<p>Since <?php echo $viewContext->user->name ?>&rsquo;s <?php echo Media::toString($viewContext->media) ?> list is marked as private, we can&rsquo;t reveal its content by showing suggestions.<br>
			If this is your list, click <a target="_blank" href="http://myanimelist.net/editprofile.php?go=listpreferences">here</a> to change privacy settings.</p>
		<?php else: ?>
			<table>
				<thead>
					<tr>
						<th class="subject">You've <?php echo $viewContext->media == Media::Anime ? 'watched' : 'read' ?> this&hellip;</th>
						<th class="proposed">&hellip;so you might want to check this:</th>
					</tr>
				</thead>
				<?php foreach ($viewContext->franchises as $franchise): ?>
					<tbody>
						<tr>
							<td class="subject">
								<ul>
									<?php foreach ($franchise->ownEntries as $entry): ?>
										<li>
											<a target="_blank" href="<?php echo $entry->mal_link ?>" title="<?php echo $entry->title ?>">
												<?php if ($entry->publishing_status == MediaStatus::NotYetPublished): ?>
													<?php if ($entry->status == UserListStatus::Planned): ?>
														<i class="icon-cross-schedule"></i>
													<?php else: ?>
														<i class="icon-cross"></i>
													<?php endif ?>
												<?php elseif ($entry->status == UserListStatus::Planned): ?>
													<i class="icon-schedule"></i>
												<?php else: ?>
													<i class="icon-empty"></i>
												<?php endif ?>
												<?php echo $entry->title ?>
											</a>
										</li>
									<?php endforeach ?>
								</ul>
							</td>
							<td class="proposed">
								<ul>
									<?php foreach ($franchise->allEntries as $entry): ?>
										<li>
											<a target="_blank" href="<?php echo $entry->mal_link ?>" title="<?php echo $entry->title ?>">
												<?php if ($entry->publishing_status == MediaStatus::NotYetPublished): ?>
													<i class="icon-cross"></i>
												<?php else: ?>
													<i class="icon-empty"></i>
												<?php endif ?>
												<?php echo $entry->title ?>
											</a>
										</li>
									<?php endforeach ?>
								</ul>
							</td>
						</tr>
					</tbody>
				<?php endforeach ?>
			</table>
		<?php endif ?>
	</div>
</div>
