<div class="section creators">
	<h2>
		<?php if ($viewContext->media == Media::Manga): ?>
			Favorite authors
		<?php elseif ($viewContext->media == Media::Anime): ?>
			Favorite studios
		<?php else: ?>
			<?php continue ?>
		<?php endif ?>
	</h2>
	<div class="section-body">
		<?php if ($viewContext->favCreators->getLargestGroupSize() == 0): ?>
			<p>Looks like there are no known creators for this user.</p>
			<p>Add a few titles and come back in 24 hours.<br>We'll be waiting for you.</p>
		<?php else: ?>
			<div class="scrollable">
				<table class="tablesorter">
					<thead>
						<tr>
							<th class="ord">#</th>
							<th class="title">Name</th>
							<th class="count" data-tooltip="Count of titles from given creator.">C</th>
							<th class="mean" data-tooltip="Mean score of given creator.">M</th>
							<th class="value" data-tooltip="Weighted score of given creator.">W</th>
							<th class="time">Time</th>
						</tr>
					</thead>
					<tbody>
					<?php $i = 1 ?>
					<?php foreach ($viewContext->favCreators->getGroupsKeys() as $creator): ?>
						<?php $entries = $viewContext->favCreators->getGroupEntries($creator) ?>
						<tr>
							<td class="ord"><?php echo $i ++ ?></td>
							<td class="title">
								<a target="_blank"
									<?php if ($viewContext->media == Media::Manga): ?>
										href="http://myanimelist.net/people/<?php echo $creator->getID() ?>/"
									<?php else: ?>
										href="http://myanimelist.net/anime.php?p=<?php echo $creator->getID() ?>"
									<?php endif ?>
								>
									<i class="icon-pop-out"></i>
								</a>
								&nbsp;
								<a class="more-trigger" data-id="<?php echo $creator->getID() ?>" href="#">
									<?php echo htmlspecialchars($creator->getName()) ?>
								</a>
							</td>
							<td class="count"><?php printf('%d', count($entries)) ?></td>
							<td class="mean">
								<?php if ($viewContext->creatorScores[$creator->getID()] == 0): ?>
									-
								<?php else: ?>
									<?php printf('%.02f', $viewContext->creatorScores[$creator->getID()]) ?>
								<?php endif ?>
							</td>
							<td class="value"><?php printf('%.02f', $viewContext->creatorValues[(string) $creator]) ?></td>
							<td class="time"><?php printf('%.02f', $viewContext->creatorTimeSpent[$creator->getID()] / 60.0) ?>h</td>
						</tr>
					<?php endforeach ?>
				</table>
				<div class="clear"></div>
			</div>

			<div class="entries-wrapper">
			</div>
		<?php endif ?>
	</div>
</div>

<script type="text/javascript">
	$('.creators .more-trigger').click(function(e) {
		e.preventDefault();
		toggleEntries($('.creators .entries-wrapper'), {'sender': 'creator', 'creator': $(this).attr('data-id')});
	});
</script>
