<div class="section score-length-dist">
	<h2>
		<?php if ($viewContext->media == Media::Anime): ?>
			<i data-tooltip="Do you prefer longer or shorter|series? (Movies are not counted.)" class="icon-tooltip"></i>
		<?php else: ?>
			<i data-tooltip="Do you prefer longer|or shorter series?" class="icon-tooltip"></i>
		<?php endif ?>
		Ratings vs. <?php echo $viewContext->media == Media::Anime ? 'episode' : 'chapter' ?> count
	</h2>
	<div class="section-body">
		<?php if ($viewContext->ratingDistribution->getLargestGroupSize() == 0): ?>
			<p>There is no information about any titles for this user.</p>
			<p>Add a few titles and come back in 24 hours.<br>We'll be waiting for you.</p>
		<?php else: ?>
			<ul class="infobox">
				<li>
					<div>
						<?php $scores = array_map(function($entries) { return Retriever::getMeanScore($entries); }, $viewContext->lengthDistribution->getGroupsEntries()) ?>
						<?php $key = array_search(max($scores), $scores) ?>
						<?php if ($viewContext->media == Media::Anime): ?>
							<?php list($num, $txt) = explode(' ', Retriever::getEpisodesText(str_replace('-', '&nbsp;to&nbsp;', $key))) ?>
						<?php elseif ($viewContext->media == Media::Manga): ?>
							<?php list($num, $txt) = explode(' ', Retriever::getChaptersText(str_replace('-', '&nbsp;to&nbsp;', $key))) ?>
						<?php endif ?>
						<span class="prefix">Highest mean</span>
						<span class="subject"><?php printf('%.2f', $scores[$key]) ?></span>
					</div>
				</li>

				<li>
					<div>
						<?php if ($viewContext->media == Media::Anime): ?>
							<?php list($num, $txt) = explode(' ', Retriever::getEpisodesText($key)) ?>
						<?php elseif ($viewContext->media == Media::Manga): ?>
							<?php list($num, $txt) = explode(' ', Retriever::getChaptersText($key)) ?>
						<?php endif ?>
						<span class="prefix">Which is</span>
						<span class="subject"><?php echo $num ?></span>
						<span class="suffix"><?php echo $txt ?></span>
					</div>
				</li>
			</ul>

			<div class="target-wrapper">
				<div class="target"></div>
				<div class="clear"></div>
			</div>

			<div class="entries-wrapper">
			</div>

			<script type="text/javascript">
				var chart = new Highcharts.Chart({
					chart: { renderTo: $('.score-length-dist .target')[0], type: 'line', marginTop: 15, marginRight: 15 },
					xAxis: {
						categories: <?php echo json_encode($viewContext->lengthDistribution->getGroupsKeys()) ?>,
						labels: { rotation: -45, align: 'right' },
						title: { text: '<?php echo $viewContext->media == Media::Anime ? 'Episode' : 'Chapter' ?> count', margin: 15 } },
					yAxis: { title: { text: 'Mean score', margin: 15 } },
					tooltip: { formatter: function() {
						var text;
						if (this.x == '?') {
							text = 'Mean score for titles of unknown length: ';
						} else {
							text = 'Mean score for titles of length ' + this.x + ': ';
						}
						if (this.y > 0) {
							text += this.y.toFixed(2);
						} else {
							text += 'unrated!';
						}
						return text;
					} },
					series: [ {
						data: <?php echo json_encode(array_values($scores)) ?>,
						point: { events: { click: function(e) {
							toggleEntries($('.score-length-dist .entries-wrapper'), {'sender': 'length', 'filter-param': this.category});
						} } }
					} ]
				});
			</script>
		<?php endif ?>
	</div>
</div>
