<div class="actions">
	<div>
		<ul class="action">
			<?php if ($viewContext->module == 'UserControllerProfileModule'): ?>
				<li class="active">
			<?php else: ?>
				<li>
			<?php endif ?>
				<a class="waitable" href="<?php echo UserControllerProfileModule::url($viewContext->userName) ?>">
					<?php echo UserControllerProfileModule::getText(null) ?>
				</a>
			</li>
		</ul>
	</div>
	<?php foreach (Media::getConstList() as $media): ?>
		<hr>
		<div>
			<ul class="action">
				<?php foreach (UserController::getAvailableModules() as $module): ?>
					<?php if (in_array($media, $module::getMediaAvailability())): ?>
						<?php if ($viewContext->module == $module and $viewContext->media == $media): ?>
							<li class="active">
						<?php else: ?>
							<li>
						<?php endif ?>
							<a class="waitable" href="<?php echo $module::url($viewContext->userName, $media) ?>">
								<?php echo $module::getText($media) ?>
							</a>
						</li>
					<?php endif ?>
				<?php endforeach ?>
			</ul>
		</div>
	<?php endforeach ?>
	<div class="clear"></div>
</div>

<!--
<div class="share">
	<p>Share:</p>
	<ul>
		<li>
			<a data-tooltip="Share on Twitter" href="https://twitter.com/intent/tweet?url=<?php echo rawurlencode(UrlHelper::currentUrl()) ?>">
				<i class="icon-twitter"></i>
			</a>
		</li>
		<li>
			<a data-tooltip="Share on Facebook" href="http://www.facebook.com/sharer.php?u=<?php echo rawurlencode(UrlHelper::currentUrl()) ?>&amp;t=Share+MALgraph">
				<i class="icon-facebook"></i>
			</a>
		</li>
	</ul>
</div>
-->

<input type="hidden" id="user-id" value="<?php echo $viewContext->userId ?>">
<input type="hidden" id="user-name" value="<?php echo $viewContext->userName ?>">
<input type="hidden" id="media" value="<?php echo Media::toString($viewContext->media) ?>">
