<div class="section achi">
	<h2>
		<i data-tooltip="Wall of badges you earned|for achieving something big." class="icon-tooltip"></i>
		Achievements
	</h2>
	<div class="section-body">
		<?php if (empty($viewContext->achievements)): ?>
			<p>No achievements yet! Better get to <?php echo $viewContext->media == Media::Manga ? 'reading' : 'watching' ?>.</p>
		<?php else: ?>
			<?php foreach ($viewContext->achievements as $ach): ?>
				<div class="achi-entry<?php if ($ach->hidden) echo ' hidden' ?>">
					<?php if (!empty($ach->path)): ?>
						<img class="achi<?php if (!empty($ach->entries)): ?> more-trigger<?php endif ?>" alt="<?php echo $ach->title ?>" src="<?php echo UrlHelper::absoluteUrl('/media/img/ach/' . $ach->path) ?>">
					<?php endif ?>
					<?php if (!empty($ach->level)): ?>
						<p class="level"><?php echo $ach->level ?></p>
					<?php endif ?>
					<h3>
						<?php echo $ach->title ?>
					</h3>

					<?php if (isset($ach->progress)): ?>
						<?php if (isset($ach->tooltip)): ?>
							<div class="progress-wrapper" data-tooltip="<?php echo ChibiRegistry::getHelper('mg')->replaceTokens($ach->tooltip, $ach) ?>">
						<?php elseif (!empty($ach->next->thresholdLeft)): ?>
							<div class="progress-wrapper" data-tooltip="Got <?php echo $ach->subject ?>, next level at <?php echo $ach->next->thresholdLeft ?>">
						<?php else: ?>
							<div class="progress-wrapper" data-tooltip="Maximum level!">
						<?php endif ?>
							<div class="progress">
								<div class="bar" style="width: <?php echo $ach->progress ?>%"></div>
							</div>
						</div>
					<?php endif ?>

					<?php if (!empty($ach->desc)): ?>
						<p class="desc"><?php echo $ach->desc ?></p>
					<?php endif ?>

					<div class="clear"></div>

					<?php if (!empty($ach->entries)): ?>
						<div class="entries-wrapper singular">
							<p>
								<a class="close"><i class="icon-close"></i></a>
								<?php if ($viewContext->private): ?>
									Can&rsquo;t show you titles from a private list.</p>
								<?php else: ?>
									Awarded for
									&nbsp;<?php echo $viewContext->media == Media::Manga ? 'reading' : 'watching' ?> these:
									&nbsp;(<?php echo count($ach->entries) ?>)
								<?php endif ?>
							</p>
							<?php if (!$viewContext->private): ?>
								<ul>
									<?php foreach ($ach->entries as $e): ?>
										<li>
											<a target="_blank" href="<?php echo $e->mal_link ?>">
												<?php echo $e->title ?>
											</a>
										</li>
									<?php endforeach ?>
								</ul>
							<?php endif ?>
						</div>
					<?php endif ?>

					<div class="clear"></div>
				</div>
			<?php endforeach ?>
		<?php endif ?>
	</div>
	<?php if ($viewContext->anyHidden): ?>
		<div>
			<p>You can also <a href="#" class="toggle-hidden">show</a> achievements from previously earned levels.</p>
		</div>
	<?php endif ?>
</div>
