<div class="section new-recommendations">
	<h2>Recommendations</h2>
	<div class="section-body">
		<?php if (empty($viewContext->newRecommendations)): ?>
			<p>Sorry, no new recommendations. Hey, this shouldn&rsquo;t have happened!</p>
		<?php else: ?>
			<table style="width: 100%">
				<thead>
					<tr>
						<th>Title</th>
						<th data-tooltip="Average score">Avg</th>
						<th data-tooltip="Hypothetical score">HS</th>
					</tr>
				</thead>
				<tbody>
					<?php foreach ($viewContext->newRecommendations as $entry): ?>
						<tr>
							<td>
								<a href="<?php echo $entry->mal_link ?>">
								<?php echo $entry->title ?>
								</a>
							</td>
							<td><?php printf('%.02f', $entry->average_score) ?></td>
							<td><?php printf('%.02f', $entry->hypotheticalScore) ?></td>
						</tr>
					<?php endforeach ?>
				</tbody>
			</table>
		<?php endif ?>
	</div>
</div>
