<div class="section missing">
	<h2>
		Missing titles
	</h2>
	<p class="undelete">There are <strong>0</strong> hidden suggestions. <a href="#">Show them</a></p>
	<div class="section-body">
		<?php if (empty($viewContext->franchises)): ?>
			<p>Yay! No missing relations!</p>
		<?php elseif ($viewContext->private): ?>
			<p>Since <?php echo $viewContext->user->name ?>&rsquo;s <?php echo Media::toString($viewContext->media) ?> list is marked as private, we can&rsquo;t reveal its content by showing suggestions.<br>
			If this is your list, click <a target="_blank" href="http://myanimelist.net/editprofile.php?go=listpreferences">here</a> to change privacy settings.</p>
		<?php else: ?>
			<table>
				<thead>
					<tr>
						<th class="subject">You've <?php echo $viewContext->media == Media::Anime ? 'watched' : 'read' ?> this&hellip;</th>
						<th class="proposed">&hellip;so you might want to check this:</th>
					</tr>
				</thead>
				<?php foreach ($viewContext->franchises as $franchise): ?>
					<tbody>
						<tr>
							<td class="subject">
								<ul>
									<?php foreach ($franchise->ownEntries as $entry): ?>
										<li>
											<a target="_blank" href="<?php echo $entry->mal_link ?>" title="<?php echo $entry->title ?>">
												<?php if ($entry->status == UserListStatus::Planned): ?>
													<i data-tooltip="Planned" class="left icon-status-planned"></i>
												<?php elseif ($entry->publishing_status == MediaStatus::NotYetPublished): ?>
													<i data-tooltip="Not yet <?php echo $viewContext->media == Media::Anime ? 'aired' : 'published' ?>" class="left icon-not-yet-aired"></i>
												<?php else: ?>
													<i class="left icon-empty"></i>
												<?php endif ?>
												<?php echo $entry->title ?>
											</a>
										</li>
									<?php endforeach ?>
								</ul>
							</td>
							<td class="proposed">
								<ul>
									<?php foreach ($franchise->allEntries as $entry): ?>
										<li id="<?php printf('mis-%s-%s%d', strtolower($viewContext->user->name), $entry->media, $entry->mal_id) ?>">
											<a href="#" class="delete">
												<i data-tooltip="Hide this suggestion" class="right icon-small-close"></i>
											</a>
											<a target="_blank" href="<?php echo $entry->mal_link ?>" title="<?php echo $entry->title ?>">
												<?php if ($entry->publishing_status == MediaStatus::NotYetPublished): ?>
													<i data-tooltip="Not yet <?php echo $viewContext->media == Media::Anime ? 'aired' : 'published' ?>" class="left icon-not-yet-aired"></i>
												<?php else: ?>
													<i class="left icon-empty"></i>
												<?php endif ?>
												<?php echo $entry->title ?>
											</a>
										</li>
									<?php endforeach ?>
								</ul>
							</td>
						</tr>
					</tbody>
				<?php endforeach ?>
			</table>
		<?php endif ?>
	</div>
</div>
